# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Yasen
tagline:          "Yet Another Selenium Enhancer"
description:      "A Selenium wrapper that is lazy enough to not search prematurely and smart enough to find all that is lost"
url:              "http://yasen.dev"
baseurl:          /

author:
  name:           "Alexei Barantsev"
  url:            "https://github.com/barancev"

# Custom vars
version:          "0.0.0"

github:
  repo:           "https://github.com/barancev/yasen"
